liflines_load;
concentration_load;

disp("Exporting results/liflines.tsv...");
f = fopen("results/liflines.tsv", "w");
fdisp(f, "wl[nm]\tA32\tB13\teff");
D = horzcat(...
	liflines.wl,...
	liflines.A32,...
	liflines.B13,...
	conc.cameraeff.at_wavelen(liflines.wl)...
);
dlmwrite(f, D, "\t");
fclose(f);
