liflines_load;
concentration_load;

disp("Exporting results/liflines.tsv...");
f = fopen("results/liflines.tsv", "w");
fdisp(f, "wl[nm]\tA32\tB13\tT\teff");
D = horzcat(...
	conc.liflines.wl,...
	conc.liflines.A32,...
	conc.liflines.B13,...
	conc.liflines.T,...
	conc.liflines.eff...
);
dlmwrite(f, D, "\t");
fclose(f);
